
import Kitap.*;
import KutuphaneOtomasyon.DbHelper;
import Kitap.Kitap;
import Kitap.KitapIslemler;
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class KitapIslemleri extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form KitapIslemleri
     */
    public KitapIslemleri() {
        try {
            initComponents();
            refreshTable(this.getKitap());
        } catch (Exception e) {
        }
    }

    public void refreshTable(ArrayList<Kitap> array) {
        model = (DefaultTableModel) KitapTablo.getModel();
        model.setRowCount(0);
        try {
            ArrayList<Kitap> kitaplar = array;
            for (Kitap kitap : kitaplar) {
                Object[] row = {kitap.getId(), kitap.getAd(), kitap.getYazar(), kitap.getYayinevi(), kitap.getTur(), kitap.getBarkod(), kitap.getRafNo()};
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }

    public ArrayList<Kitap> getKitap() throws SQLException {
        KitapIslemler islemler = new KitapIslemler();
        return islemler.Listele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kitap_ekle = new javax.swing.JButton();
        kitap_duzenle = new javax.swing.JButton();
        kitap_sil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        KitapTablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kitap_adi = new javax.swing.JTextField();
        kitap_yazari = new javax.swing.JTextField();
        kitap_yayinevi = new javax.swing.JTextField();
        kitap_turu = new javax.swing.JTextField();
        kitap_barkod = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        kitap_ara = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        kitap_rafno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        kitap_ekle.setText("Kitap Ekle");
        kitap_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_ekleActionPerformed(evt);
            }
        });

        kitap_duzenle.setText("Kitap Düzenle");
        kitap_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_duzenleActionPerformed(evt);
            }
        });

        kitap_sil.setText("Kitap Sil");

        KitapTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Kitap Adı", "Yazarı", "Yayınevi", "Türü", "Barkod No", "Raf No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(KitapTablo);

        jLabel1.setText("Kitap Adı");

        jLabel2.setText("Kitap Yazarı");

        jLabel3.setText("Kitap Yayınevi");

        jLabel4.setText("Kitap Türü");

        jLabel5.setText("Barkod No");

        jLabel6.setText("Raf No");

        kitap_adi.setText("jTextField1");
        kitap_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_adiActionPerformed(evt);
            }
        });

        kitap_yazari.setText("jTextField2");

        kitap_yayinevi.setText("jTextField3");

        kitap_turu.setText("jTextField4");

        kitap_barkod.setText("jTextField5");

        jTextField1.setText("jTextField1");

        kitap_ara.setText("Kitap Ara");
        kitap_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_araActionPerformed(evt);
            }
        });

        jLabel7.setText("Raf No ");

        kitap_rafno.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitap_rafno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kitap_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kitap_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kitap_yayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kitap_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kitap_yazari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kitap_duzenle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kitap_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kitap_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(kitap_ara)))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(kitap_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kitap_duzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kitap_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(kitap_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(kitap_yazari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(kitap_yayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(kitap_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(kitap_barkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(kitap_ara)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(kitap_rafno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(530, 530, 530)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kitap_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_ekleActionPerformed

        try {

            String ad = kitap_adi.getText();
            String kitap_yazar = kitap_yazari.getText();
            String kitap_yayin = kitap_yayinevi.getText();
            String tur = kitap_turu.getText();
            String barkod = kitap_barkod.getText();
            String rafno = kitap_rafno.getText();
            KitapIslemler islemler = new KitapIslemler();
            Kitap kitap = new Kitap(ad, kitap_yazar, kitap_yayin, tur, barkod, rafno);
            islemler.Ekle(kitap);
            JOptionPane.showMessageDialog(null, "Ekleme Başarılı");
            refreshTable(this.getKitap());
            //clearTextBox();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_kitap_ekleActionPerformed

    private void kitap_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_duzenleActionPerformed

        try {
            int row = KitapTablo.getSelectedRow();
            String value = (KitapTablo.getModel().getValueAt(row, 0).toString());
            String ad = kitap_adi.getText();
            String kitap_yazar = kitap_yazari.getText();
            String kitap_yayin = kitap_yayinevi.getText();
            String tur = kitap_turu.getText();
            String barkod = kitap_barkod.getText();
            String rafno = kitap_rafno.getText();
            KitapIslemler islemler = new KitapIslemler();
            Kitap kitap = new Kitap(ad, kitap_yazar, kitap_yayin, tur, barkod, rafno);
            islemler.Güncelle(kitap, Integer.parseInt(value));
            DefaultTableModel model = (DefaultTableModel) KitapTablo.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Güncelleme Başarılı");
            refreshTable(this.getKitap());
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_kitap_duzenleActionPerformed

    private void kitap_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitap_adiActionPerformed

    private void kitap_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_araActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitap_araActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            refreshTable(this.getKitap());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KitapIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KitapIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KitapIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KitapIslemleri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapIslemleri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KitapTablo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField kitap_adi;
    private javax.swing.JButton kitap_ara;
    private javax.swing.JTextField kitap_barkod;
    private javax.swing.JButton kitap_duzenle;
    private javax.swing.JButton kitap_ekle;
    private javax.swing.JTextField kitap_rafno;
    private javax.swing.JButton kitap_sil;
    private javax.swing.JTextField kitap_turu;
    private javax.swing.JTextField kitap_yayinevi;
    private javax.swing.JTextField kitap_yazari;
    // End of variables declaration//GEN-END:variables
}
